### ISSUE TITLE
Request for Epoch Configuration Details

### ISSUE THREAD

**Issue by Facico** [zefang-liu/AdaMoLE#1]
Hi, thanks for your awesome work.
The paper mentions that the number of epochs is tuned between 1 and 20, but the repository only provides the configuration for commonsense_qa. Could you please provide the corresponding number of epochs for other datasets as well? 

Thanks!

**Comment by zefang-liu** [comment]
Hi @Facico, Here are maximum numbers of epochs we used:

- CommonsenseQA: 2
- Cosmos QA: 2
- SocialIQA: 2
- PhysicalIQA: 5 
- ScienceQA: 10
- BoolQ: 5
- CB: 10
- COPA: 10
- RTE: 15
- WiC: 16

The best model performances were selected within these ranges.
